GET  http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/66cbc57a698012766b5e3d7c

###
GET http://localhost:3001/api/persons/info

###

DELETE http://localhost:3001/api/persons/66c794c874f72bd385bb9c5a


### 
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Joel Dodd",
    "number": "1234567890"
}
###
PUT http://localhost:3001/api/persons/66cbc57a698012766b5e3d7c
Content-Type: application/json

{
    "name": "Joel Dodd",
    "number": "1234567890"
}

